import ProjectDescription
import ProjectDescriptionHelpers

let workspace: Workspace = .init(
    name: "PhotoEditingApp",
    projects: ["**"],
    schemes: [],
    fileHeaderTemplate: nil,
    additionalFiles: [],
    generationOptions: .options(
        enableAutomaticXcodeSchemes: false,
        autogeneratedWorkspaceSchemes: .disabled,
        lastXcodeUpgradeCheck: nil,
        renderMarkdownReadme: false
    )
)
